#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
feh --bg-fill /home/david/city.jpg &
wal -i /home/david/city.jpg &
polybar mybar &

#. "${HOME}/.cache/wal/colors.sh"
. "/home/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"

bspc config focus_follows_pointer true

#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 一 二 三 四 五 六 七 八

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config border_width        10
bspc config window_gap          50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 2
bspc config window_gap 25
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
